#!/usr/bin/env python3
"""L-Reports — Auto Report Generation"""
import os, sys, json, time, threading
from datetime import datetime, timedelta
from collections import Counter

HOME = os.path.expanduser("~")
BASE = os.path.join(HOME, "vorix-hybrid/phone")
REPORT_DIR = os.path.join(BASE, "reports")
STATE_FILE = os.path.join(BASE, "layer_reports_state.json")

os.makedirs(REPORT_DIR, exist_ok=True)

try:
    import requests
    with open(os.path.join(HOME, "vorix/.tg-token")) as f:
        TG = f.read().strip()
except:
    TG = ""
CHAT = "175160049"

CONFIG = {
    "auto_generate_hours": 6,     # هر ۶ ساعت
    "daily_report_hour": 8,        # روزانه ساعت ۸ صبح
    "send_to_telegram": True,
}


class Reports:
    def __init__(self):
        self.stats = {"generated": 0, "sent": 0, "started": time.time()}
        self.load_state()

    def load_state(self):
        try:
            with open(STATE_FILE) as f:
                s = json.load(f)
                self.stats = s.get("stats", self.stats)
        except: pass

    def save_state(self):
        try:
            with open(STATE_FILE, "w") as f:
                json.dump({"stats": self.stats}, f, indent=2)
        except: pass

    def collect_stats(self):
        """جمع‌آوری آمار از همه لایه‌ها"""
        stats = {"timestamp": datetime.now().isoformat()}
        
        # Blocklist
        try:
            with open(os.path.join(BASE, "blocklist.json")) as f:
                blocked = json.load(f)
                stats["blocked_ips"] = len(blocked)
                stats["permanent_blocks"] = sum(1 for v in blocked.values() if v.get("type") == "perm")
        except:
            stats["blocked_ips"] = 0
            stats["permanent_blocks"] = 0
        
        # Layer states
        layer_files = {
            "threat_intel": "layer02_state.json",
            "behavioral": "layer03_state.json",
            "rate_limit": "layer09_state.json",
            "network": "layer08_state.json",
            "identity": "layer29_30_state.json",
            "self_defense": "layer01_state.json",
            "watchdog": "watchdog_state.json",
            "ml": "layer21_state.json",
        }
        
        for name, fname in layer_files.items():
            try:
                with open(os.path.join(BASE, fname)) as f:
                    data = json.load(f)
                    stats[name] = data.get("stats", {})
            except:
                stats[name] = {"status": "no_data"}
        
        # Events summary
        try:
            qfile = os.path.join(BASE, "queue.jsonl")
            if os.path.exists(qfile):
                with open(qfile) as f:
                    lines = f.readlines()
                    stats["queue_events"] = len(lines)
                    
                    # Counter by severity
                    sev = Counter()
                    attacks = Counter()
                    for line in lines[-1000:]:
                        try:
                            e = json.loads(line)
                            sev[e.get("severity", "?")] += 1
                            attacks[e.get("event_type", "?")] += 1
                        except: pass
                    stats["severity"] = dict(sev)
                    stats["top_attacks"] = dict(attacks.most_common(10))
        except: pass
        
        return stats

    def generate_report(self, period="manual"):
        """تولید گزارش"""
        stats = self.collect_stats()
        
        # Markdown report
        report = f"""# 🛡️ VORIX Security Report

**Period:** {period}
**Generated:** {stats['timestamp']}

---

## 📊 Summary

| Metric | Value |
|--------|-------|
| Blocked IPs | {stats.get('blocked_ips', 0)} |
| Permanent Blocks | {stats.get('permanent_blocks', 0)} |
| Queue Events | {stats.get('queue_events', 0)} |

---

## 🎯 Attack Distribution

"""
        sev = stats.get("severity", {})
        for level, count in sorted(sev.items(), key=lambda x: -x[1]):
            icon = {"CRITICAL": "🔴", "ERROR": "❌", "WARN": "🟡", "INFO": "✅"}.get(level, "⚪")
            report += f"- {icon} **{level}**: {count}\n"
        
        report += "\n## 🔥 Top Attack Types\n\n"
        for atype, count in list(stats.get("top_attacks", {}).items())[:10]:
            report += f"- `{atype}`: {count}\n"
        
        report += "\n## 🛡️ Layer Status\n\n"
        for layer in ["threat_intel", "behavioral", "rate_limit", "network", "identity", "self_defense", "watchdog", "ml"]:
            data = stats.get(layer, {})
            status = "✅" if data and "status" not in data else "⚠️"
            report += f"- {status} **{layer}**: {data.get('started', 'unknown')}\n"
        
        report += f"\n---\n\n_Generated by VORIX Security_ 🛡️\n"
        
        # ذخیره
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        path = os.path.join(REPORT_DIR, f"report_{period}_{ts}.md")
        with open(path, "w") as f:
            f.write(report)
        
        # JSON هم
        json_path = path.replace(".md", ".json")
        with open(json_path, "w") as f:
            json.dump(stats, f, indent=2, default=str)
        
        self.stats["generated"] += 1
        self.save_state()
        
        return path, report

    def send_report(self, path, report):
        """ارسال به تلگرام"""
        if not CONFIG["send_to_telegram"] or not TG:
            return False
        
        try:
            # خلاصه برای تلگرام (فقط بخش اول)
            summary = report[:3500]
            
            requests.post(
                f"https://api.telegram.org/bot{TG}/sendMessage",
                json={
                    "chat_id": CHAT,
                    "text": f"📊 *VORIX Report*\n\n{summary}",
                    "parse_mode": "Markdown"
                },
                timeout=15
            )
            self.stats["sent"] += 1
            return True
        except: pass
        return False

    def auto_loop(self):
        """حلقه خودکار"""
        print(f"📊 Auto Reports — every {CONFIG['auto_generate_hours']}h")
        
        last_report = 0
        last_daily = 0
        
        while True:
            try:
                now = time.time()
                
                # گزارش دوره‌ای
                if now - last_report > CONFIG["auto_generate_hours"] * 3600:
                    path, report = self.generate_report("periodic")
                    self.send_report(path, report)
                    print(f"📊 Report generated: {os.path.basename(path)}")
                    last_report = now
                
                # گزارش روزانه صبح
                h = datetime.now().hour
                if h == CONFIG["daily_report_hour"] and now - last_daily > 86400:
                    path, report = self.generate_report("daily")
                    self.send_report(path, report)
                    print(f"📊 Daily report: {os.path.basename(path)}")
                    last_daily = now
                
                time.sleep(300)
            except KeyboardInterrupt:
                break
            except Exception as e:
                print(f"⚠️ {e}")
                time.sleep(600)

    def status(self):
        uptime = int(time.time() - self.stats["started"])
        files = [f for f in os.listdir(REPORT_DIR) if f.endswith(".md")] if os.path.exists(REPORT_DIR) else []
        
        print(f"\n📊 L-Reports")
        print(f"═══════════════════════════════")
        print(f"Generated:   {self.stats['generated']}")
        print(f"Sent:        {self.stats['sent']}")
        print(f"Files:       {len(files)}")
        print(f"Uptime:      {uptime // 3600}h {(uptime // 60) % 60}m")

    def test(self):
        print("🧪 Testing Reports\n")
        path, report = self.generate_report("test")
        print(f"✅ Report: {os.path.basename(path)}")
        print()
        print("--- Preview ---")
        print(report[:800])
        print("...")


def main():
    if len(sys.argv) < 2:
        print("Usage: layer_reports.py {test|status|generate|watch}")
        return
    cmd = sys.argv[1]
    rp = Reports()
    
    if cmd == "test": rp.test()
    elif cmd == "status": rp.status()
    elif cmd == "generate": 
        p, r = rp.generate_report("manual")
        print(f"✅ {p}")
    elif cmd == "watch": rp.auto_loop()

if __name__ == "__main__":
    main()
